version: '3'
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: mqZWhLi
      POSTGRES_USER: postgres

  backend:
    image: "node:latest"
    working_dir: /usr/src/app
    command: ./run-dev.sh
    volumes:
     - ./backend:/usr/src/app
    depends_on:
     - postgres
    environment:
      RDS_DB_NAME: db
      RDS_HOSTNAME: postgres
      RDS_PASSWORD: mqZWhLi
      RDS_USERNAME: postgres
      RDS_PORT: 5432
    ports:
     - "9229:9229"
    expose:
     - "9229"

  app:
    image: "node:latest"
    working_dir: /usr/src/app
    command: ./run-dev.sh
    volumes:
     - ./app:/usr/src/app

  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app
     - backend
