version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: mqZWhLi
      POSTGRES_USER: postgres

  app-api:
    image: "node:latest"
    working_dir: /usr/src/app
    command: ./run-dev.sh
    volumes:
     - ./api:/usr/src/app
    depends_on:
     - db
    environment:
      PGDATABASE: db
      PGHOST: db
      PGPASSWORD: mqZWhLi
      PGUSER: postgres
    ports:
     - "9229:9229"
    expose:
     - "9229"

  app-ui:
    image: "node:latest"
    working_dir: /usr/src/app
    command: ./run-dev.sh
    volumes:
     - ./ui:/usr/src/app

  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app-ui
     - app-api
